#! /bin/bash

# Backup work directory


# 1: 
# Create work_YYYY_DDMM.tar.gz in the Backups folder


# Folders
work_dir=$HOME/work/*
bckp_dir=$HOME/Backups
dbox_dir=$HOME/Dropbox/Backups
snap_dir=$HOME/Backups/Snap



# Create backup
echo ":: Creating backup for work ..."


backup_name="work_"$(date +%Y)"_"$(date +%b)"_"$(date +%d)".tar.gz"


# create tar file
tar -cvzf $backup_folder/$backup_name $work_folder

echo ":: Done. Backup was created in Backups folder"



