#! /usr/bin/env python

import os, sys
import subprocess as sp

backlight_path = '/sys/class/leds/asus::kbd_backlight'
step = 1

if not os.path.isdir(backlight_path):
    backlight_path = '/sys/devices/platform/asus-nb-wmi/leds/asus::kbd_backlight'

def get_current_brightness():
    with open(os.path.join(backlight_path,'brightness')) as curr_file:
        return int(curr_file.read().split('\n')[0])


def get_max_brightness():
    with open(os.path.join(backlight_path,'max_brightness')) as max_file:
        return int(max_file.read().split('\n')[0])


def main():

    current_value = get_current_brightness()
    max_value = get_max_brightness()

    if len(sys.argv) < 2:
        print("usage: kbdbacklight [up|down]")
        exit(1)

    if sys.argv[1] == "up":
        new_value = current_value + step
    elif sys.argv[1] == "down":
        new_value = current_value - step

    if new_value > max_value:
        new_value = max_value
    elif new_value < 0:
        new_value = 0

    with open(os.path.join(backlight_path,'brightness'), 'w') as f:
        f.write(str(new_value))


    percentage = int(new_value * 100 / max_value)

    sp.call(['osdify', '-p', str(percentage)])


if __name__ == '__main__':
    main()
