#! /bin/bash
# open file with the correponding app.
# usage: open [files]

# if not file is passed, open current dir with emacs.
if [ $# -eq 0 ] ; then
    $EDITOR .
    exit 0
fi

get_mimetype() {
    file --mime-type -b "${1}" | cut -d / -f 1
}

get_extension() {
    echo "${1##*.}"
}

get_app() {

    # first try using extensions
    ext=$(get_extension "${1}")

    case $ext in
        # text
        txt|sh|c|cpp|cxx|tex|h|py|cc|log)
            app="$EDITOR" ;;

        # archive
        tar|gz|rar|zip|7z|lha|bz2|tgz)
            app="ark" ;;

        # video
        mkv|mpe?g|mkv|avi|mp4|wmv|rmvb|as[fx]|divx|vob|ogm|ra?m|flv|part|iso)
            app="mpv" ;;

        #audio
        mp3|wav|ogg)
            app="mpv" ;;

        #torrent
        torrent)
            app="transmission-qt" ;;

        #pdf
        pdf|ps|djvu)
            app="okular" ;;

        #eps
        eps)
            app="evince" ;;

        #images
        png|jpg|jpeg|JPG|JPEG|gif)
            app="gwenview" ;;
        ##command -v sxiv >/dev/null 2>&1 && app="sxiv" || app="display" ;;

        #html
        html?|swf)
            app=$BROWSER ;;
    esac

    if [[ -n "$1" ]] ; then
        echo "$app"
        return 0
    fi

    # if not app, use mimetype
    mimetype=$(get_mimetype "${1}")

    case $mimetype in
        text)
            app="$EDITOR" ;;
        image)
            app="gwenview" ;;
    esac

    if [[ -n "$1" ]] ; then
        echo "$app"
        return 0
    fi

    return 1
}

# args: app, file
open() {
    setsid setsid "${1}" "${2}" > /dev/null 2>&1
}

# if only one file
if [ "$#" -eq 1 ] ; then
    app=$(get_app "${@}")
    open "${app}" "${@}"

else
    while [[ "${1}" ]] ; do
        app=$(get_app "${1}")
        open "${app}" "${1}"
        shift
    done
fi
