#! /usr/bin/env bash
# play radio metro :)

url=mms://201.212.5.144/metro
#url=mms://201.212.5.144/audio959-rockandpop

while :
do
    notify-send "Playing Metro 95.3 :)"
    mplayer $url
    sleep 5
done
