#! /usr/bin/env bash
# play radio metro :)

url=mms://201.212.5.144/metro
#url=mms://201.212.5.144/audio959-rockandpop

while :
do
    notify-send "Playing Metro 95.1"
    mplayer $url -cache 1000
    #-dumpstream -dumpfile recital_muse.asf
    sleep 2
done


# TMPFILE="metro"

# # create pipe
# mkfifo $TMPFILE

# # read stream from pipe and send it to file and mplayer
# cat $TMPFILE | tee -a -i video.asf | mplayer - &

# # send data to pipe
# mplayer $url -dumpstream -dumpfile $TMPFILE
