#!/bin/bash

devices=$(xrandr -q | grep [[:upper:]]1)

# availableopts[0]="laptop"

function check_vga () {
    return
    }

# if [[ $devices == *"VGA1 connected"* ]] ; then
#     availableopts[1]="vga"
# fi

# if [[ $devices == *"HDMI1 connected"* ]] ; then
#     availableopts[1]="HDMI"
# fi

function connect_laptop () {
    xrandr --output eDP1 --auto
    xrandr --output HDMI1 --off
    xrandr --output VGA1  --off
}

function connect_vga () {
    xrandr --output VGA1  --auto
    xrandr --output eDP1  --off
    xrandr --output HDMI1 --off
}

function connect_hdmi () {
    xrandr --output HDMI1 --auto
    xrandr --output VGA1  --off
    xrandr --output eDP1  --off
}

file="${HOME}/.current_screen"

echo $devices

if grep -q laptop "$file"; then

    if [[ $devices == *"HDMI1"* ]] ; then
        connect_hdmi
        echo hdmi > "$file"
    elif [[ $devices == *"VGA1 connected"* ]] ; then
        connect_vga
        echo vga > "$file"
    fi

elif grep -q vga "$file" ; then
#     connect_laptop
#     echo laptop > "$file"
# fi

# pactl set-card-profile 0 output:hdmi-stereo
# output:analog-stereo+input:analog-stereo
