#!/bin/bash
# timer

if [ $# -eq 0 ] ; then
    echo "[timer] Usage: timer <time>"
    exit 1
fi

if [[ "$1" == *s ]] ; then
    wait=$(echo $1 | sed 's:s::')

elif [[ "$1" == *m ]] ; then
    min=$(echo $1 | sed 's:m::')
    wait=$(($min*60))
fi

# Wait :P
sleep $wait

# Notification! and sound?!
notify-send --urgency critical "timer" "RIIIIIIIIIIING! time is over!"
mplayer /usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga
