#! /usr/bin/env bash
# todo list

todofile=$HOME/.todo

test -f $todofile || touch $todofile

if test $# = 0 ; then
    cat $todofile

elif test $1 = -l ; then
    cat -n $todofile

elif test $1 = -c ; then
    > $todofile

elif test $1 = -r ; then 
    cat -n $todofile
    echo -ne "----------------------------\nType a number to remove: "
    read NUMBER
    sed -ie ${NUMBER}d $todofile

else
    echo $@ >> $todofile
fi
